version: '3.3'
services:
  clamav:
    image: 'clamav/clamav:0.104.1'
    restart: 'always'
    volumes:
    - 'clamav:/var/lib/clamav'
    - './etc/clamav/clamd.conf:/etc/clamav/clamd.conf:ro'
    - './etc/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro'
volumes:
  clamav:
